# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmulti.proto\x12\rdownloadshort\"\x1c\n\rParamsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x0cReturnsReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbf\x02\n\rDownloadShort\x12I\n\nDownTiktok\x12\x1c.downloadshort.ParamsRequest\x1a\x1b.downloadshort.ReturnsReply\"\x00\x12J\n\x0b\x44ownYoutube\x12\x1c.downloadshort.ParamsRequest\x1a\x1b.downloadshort.ReturnsReply\"\x00\x12I\n\nInfoTiktok\x12\x1c.downloadshort.ParamsRequest\x1a\x1b.downloadshort.ReturnsReply\"\x00\x12L\n\rDownTiktokAlt\x12\x1c.downloadshort.ParamsRequest\x1a\x1b.downloadshort.ReturnsReply\"\x00\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_PARAMSREQUEST']._serialized_start=30
  _globals['_PARAMSREQUEST']._serialized_end=58
  _globals['_RETURNSREPLY']._serialized_start=60
  _globals['_RETURNSREPLY']._serialized_end=90
  _globals['_DOWNLOADSHORT']._serialized_start=93
  _globals['_DOWNLOADSHORT']._serialized_end=412
# @@protoc_insertion_point(module_scope)
